wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 128
n_units:
  desc: null
  value: 512
_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1709107640.617127
    t:
      1:
      - 1
      - 5
      - 35
      - 53
      - 55
      2:
      - 1
      - 5
      - 35
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.0
      5: 0.16.3
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
