wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
epoch:
  desc: null
  value: 200
batch_size:
  desc: null
  value: 64
n_units:
  desc: null
  value: 128
update_freq:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.9.0
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1707845795.471061
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.9.0
      5: 0.16.3
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
